export const WEBSOCKET_CONFIG = {
  INITIAL_RECONNECT_DELAY: 1000,
  MAX_RECONNECT_DELAY: 30000,
  RECONNECT_MULTIPLIER: 2,
  EVENT_INTERVAL_MIN: 3000,
  EVENT_INTERVAL_MAX: 5000,
  NEW_ORDER_PROBABILITY: 0.2,
} as const;
